# Generated by Django 5.2.7 on 2026-03-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_rename_user_departmenthead_head_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editlog',
            old_name='log_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userreportsto',
            old_name='reporter',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='update_time',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='latest',
            field=models.SmallIntegerField(db_default=1, default=1),
        ),
    ]
