# Generated by Django 5.2.7 on 2026-04-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_log_user_editlog_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditLog',
            new_name='UserEditLog',
        ),
    ]
