
tasks = {   'wowo': {   'table': 'tasks_workspace',
                'model': 'WorkSpace',
                'path': 'tasks.models.workspaces',
                'type': 'o2o',
                'cols': [   'id',
                            'name',
                            'description',
                            'type',
                            'creator_id',
                            'create_time',
                            'update_time',
                            'delete_time']},
    'wolc': {   'table': 'tasks_projectlifecycle',
                'model': 'ProjectLifeCycle',
                'path': 'tasks.models.workspaces',
                'type': 'o2o',
                'cols': [   'id',
                            'start',
                            'end',
                            'interval_length',
                            'interval_type',
                            'life_cycle_type',
                            'workspace_id',
                            'create_time',
                            'delete_time',
                            'latest']},
    'wode': {   'table': 'tasks_workspacedepartment',
                'model': 'WorkSpaceDepartment',
                'path': 'tasks.models.workspaces',
                'type': 'm2m',
                'cols': [   'id',
                            'department_id',
                            'workspace_id',
                            'create_time',
                            'delete_time',
                            'latest']},
    'wous': {   'table': 'tasks_workspaceuser',
                'model': 'WorkSpaceUser',
                'path': 'tasks.models.workspaces',
                'type': 'm2m',
                'cols': ['id', 'user_id', 'workspace_id', 'create_time', 'delete_time', 'latest']},
    'wote': {   'table': 'tasks_workspaceterm',
                'model': 'WorkSpaceTerm',
                'path': 'tasks.models.workspaces',
                'type': 'rlc',
                'cols': [   'id',
                            'workspace_id',
                            'parent_id',
                            'term',
                            'term_description',
                            'create_time',
                            'update_time',
                            'delete_time']},
    'tata': {   'table': 'tasks_task',
                'model': 'Task',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': [   'id',
                            'description',
                            'creator_id',
                            'parent_id',
                            'create_time',
                            'update_time',
                            'delete_time']},
    'tade': {   'table': 'tasks_taskdetails',
                'model': 'TaskDetails',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': ['id', 'task_id', 'details', 'latest', 'create_time', 'delete_time']},
    'tadl': {   'table': 'tasks_taskdeadline',
                'model': 'TaskDeadline',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': ['id', 'task_id', 'deadline', 'latest', 'create_time', 'delete_time']},
    'tast': {   'table': 'tasks_taskstatus',
                'model': 'TaskStatus',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': ['id', 'task_id', 'status', 'latest', 'create_time', 'delete_time']},
    'tavi': {   'table': 'tasks_taskvisibility',
                'model': 'TaskVisibility',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': ['id', 'task_id', 'visibility', 'latest', 'create_time', 'delete_time']},
    'taas': {   'table': 'tasks_taskassignment',
                'model': 'TaskAssignment',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': [   'id',
                            'task_id',
                            'assignor_id',
                            'assignee_id',
                            'latest',
                            'create_time',
                            'delete_time']},
    'tawa': {   'table': 'tasks_taskwatcher',
                'model': 'TaskWatcher',
                'path': 'tasks.models.tasks',
                'type': 'm2m',
                'cols': ['id', 'task_id', 'watcher_id', 'latest', 'create_time', 'delete_time']},
    'taco': {   'table': 'tasks_taskcomment',
                'model': 'TaskComment',
                'path': 'tasks.models.tasks',
                'type': 'rlc',
                'cols': [   'id',
                            'task_id',
                            'comment',
                            'response_to_id',
                            'commenter_id',
                            'create_time',
                            'update_time',
                            'delete_time']},
    'tawo': {   'table': 'tasks_taskworkspace',
                'model': 'TaskWorkSpace',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': ['id', 'task_id', 'workspace_id', 'create_time', 'delete_time', 'latest']},
    'tate': {   'table': 'tasks_termfortask',
                'model': 'TermForTask',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': ['id', 'term_id', 'task_id', 'create_time', 'delete_time', 'latest']},
    'tapo': {   'table': 'tasks_pointsfortask',
                'model': 'PointsForTask',
                'path': 'tasks.models.tasks',
                'type': 'o2o',
                'cols': ['id', 'points', 'task_id', 'create_time', 'delete_time', 'latest']},
    'taup': {   'table': 'tasks_userpointsfortask',
                'model': 'UserPointsForTask',
                'path': 'tasks.models.tasks',
                'type': 'm2m',
                'cols': [   'id',
                            'rating',
                            'task_id',
                            'contributor_id',
                            'create_time',
                            'delete_time',
                            'latest']}}
