# Generated by Django 5.2.7 on 2026-03-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_creator_user_comment_commenter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkSpaceTasks',
            new_name='TaskWorkSpace',
        ),
    ]
