# Generated by Django 5.2.7 on 2026-03-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_workspacetasks_taskworkspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='response_to',
        ),
    ]
