# Generated by Django 5.2.7 on 2026-04-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_pointsfortask_projectlifecycle_userpointsfortask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspaceterm',
            old_name='description',
            new_name='term_description',
        ),
    ]
