# Generated by Django 5.2.7 on 2026-04-26 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_description_workspaceterm_term_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='TaskAssignment',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='TaskComment',
        ),
        migrations.RenameModel(
            old_name='Deadline',
            new_name='TaskDeadline',
        ),
        migrations.RenameModel(
            old_name='Details',
            new_name='TaskDetails',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='TaskStatus',
        ),
        migrations.RenameModel(
            old_name='Visibility',
            new_name='TaskVisibility',
        ),
        migrations.RenameModel(
            old_name='Watcher',
            new_name='TaskWatcher',
        ),
    ]
