
users = {   'usus': {   'table': 'auth_user',
                'model': 'User',
                'path': 'users.models.user',
                'type': 'o2o',
                'cols': [   'id',
                            'password',
                            'last_login',
                            'is_superuser',
                            'username',
                            'first_name',
                            'last_name',
                            'email',
                            'is_staff',
                            'user_level',
                            'is_active',
                            'date_joined',
                            'create_time',
                            'update_time',
                            'delete_time']},
    'uspr': {   'table': 'users_userprofile',
                'model': 'UserProfile',
                'path': 'users.models.user',
                'type': 'o2o',
                'cols': [   'id',
                            'user_id',
                            'legal_first_name',
                            'legal_last_name',
                            'office_phone',
                            'office_ext',
                            'cell_phone',
                            'home_phone',
                            'office_location',
                            'create_time',
                            'delete_time',
                            'latest']},
    'usse': {   'table': 'users_usersettings',
                'model': 'UserSettings',
                'path': 'users.models.user',
                'type': 'o2o',
                'cols': ['id', 'user_id', 'settings', 'create_time', 'delete_time', 'latest']},
    'usre': {   'table': 'users_userreportsto',
                'model': 'UserReportsTo',
                'path': 'users.models.user',
                'type': 'm2m',
                'cols': ['id', 'user_id', 'reportsTo_id', 'latest', 'create_time', 'delete_time']},
    'uslo': {   'table': 'users_usereditlog',
                'model': 'UserEditLog',
                'path': 'users.models.user',
                'type': 'rlc',
                'cols': [   'id',
                            'user_id',
                            'change_log',
                            'create_time',
                            'update_time',
                            'delete_time']},
    'dede': {   'table': 'users_department',
                'model': 'Department',
                'path': 'users.models.department',
                'type': 'o2o',
                'cols': [   'id',
                            'name',
                            'description',
                            'creator_id',
                            'parent_id',
                            'create_time',
                            'update_time',
                            'delete_time']},
    'deus': {   'table': 'users_departmentuser',
                'model': 'DepartmentUser',
                'path': 'users.models.department',
                'type': 'm2m',
                'cols': ['id', 'user_id', 'department_id', 'latest', 'create_time', 'delete_time']},
    'dehe': {   'table': 'users_departmenthead',
                'model': 'DepartmentHead',
                'path': 'users.models.department',
                'type': 'm2m',
                'cols': ['id', 'department_id', 'head_id', 'latest', 'create_time', 'delete_time']}}
